repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: mixed-line-ending

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file]
      - id: cpplint
        args: [--filter=-legal/copyright,-whitespace/tab]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: platformio-build
        name: PlatformIO Build Test
        entry: uv run task build
        language: system
        pass_filenames: false
        files: \.(cpp|c|h|hpp|ino)$|platformio\.ini$
        description: Run PlatformIO build to ensure code compiles
