name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**/*.cpp"
      - "src/**/*.c"
      - "src/**/*.h"
      - "src/**/*.hpp"
      - "src/**/*.ino"
      - "include/**/*.h"
      - "include/**/*.hpp"
      - "lib/**/*.cpp"
      - "lib/**/*.c"
      - "lib/**/*.h"
      - "lib/**/*.hpp"
      - "platformio.ini"
      - "pyproject.toml"
      - "**/*.md"
      - ".clang-format"
      - ".pre-commit-config.yaml"

jobs:
  claude-review:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Be constructive and helpful in your feedback.
