name: PlatformIO CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-

    - name: Build PlatformIO Project
      run: uv run task build

    - name: Upload firmware binary
      uses: actions/upload-artifact@v4
      with:
        name: firmware-m5stack-core2
        path: .pio/build/m5stack-core2/firmware.bin
        retention-days: 30

    - name: Upload ELF file
      uses: actions/upload-artifact@v4
      with:
        name: firmware-m5stack-core2-elf
        path: .pio/build/m5stack-core2/firmware.elf
        retention-days: 30
